Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.160"

    ansible.vm.provision  "shell",
      inline: "cp /vagrant/.vagrant/machines/wordpress/virtualbox/private_key /home/vagrant && \
              chmod 600 /home/vagrant/private_key && \
              chown vagrant:vagrant /home/vagrant/private_key"

    ansible.vm.provision  "shell",
      inline: "cp /vagrant/hosts /home/vagrant"

    ansible.vm.provision  "shell",
      inline: "apt update && \
              apt install -y software-properties-common && \
              add-apt-repository --yes --update ppa:ansible/ansible && \
              apt install -y ansible"
  end

  config.vm.define "wordpress" do |wp|
    wp.vm.network "public_network", ip: "192.168.1.161"
  end
end