---
- hosts: all
  handlers:
    - name: 'restart apache'
      service:
        name: apache2
        state: restarted
      become: yes
  tasks:
  - name: 'Add Repo php7.4'
    apt_repository:
      repo: 'ppa:ondrej/php'
    become: yes
  - name: 'Update Repo'
    apt:
      update_cache: yes
    become: yes
  - name: 'Install packages'
    apt: 
      name: [php7.4, apache2, libapache2-mod-php7.4, php7.4-gd, php-ssh2, php7.4-mcrypt, mysql-server, python-mysqldb, php7.4-mysql]
      state: latest
    become: yes
  - name: 'Create MySQL database'
    mysql_db:
      name: wordpress_db
      login_user: root
      state: present
    become: yes
  - name: 'Create MySQL user'
    mysql_user:
      login_user: root
      name: wordpress_user
      password: '12345'
      priv: 'wordpress_db.*:ALL'
      state: present
    become: yes
  - name: 'Download wordpress'
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz
  - name: 'Decompress wordpress'
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/
      remote_src: yes
    become: yes
  - name: 'Create wordpress config file'
    copy:
      src: /var/www/wordpress/wp-config-sample.php
      dest: /var/www/wordpress/wp-config.php
      remote_src: yes
    become: yes
  - name: 'Configure wordpress'
    replace:
      path: /var/www/wordpress/wp-config.php
      regexp: '{{ item.regex }}'
      replace: '{{ item.value }}'
    with_items:
      - { regex: 'database_name_here', value: 'wordpress_db' }
      - { regex: 'username_here', value: 'wordpress_user' }
      - { regex: 'password_here', value: '12345' }
    become: yes
  - name: 'Configure apache to serve wordpress'
    copy:
      src: files/000-default.conf
      dest: /etc/apache2/sites-available/000-default.conf
    become: yes
    notify:
      - restart apache
