Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "wordpress" do |wp|
    wp.vm.network "public_network", ip: "192.168.1.161"

    wp.vm.provision  "shell",
      inline: "apt-get update && apt-get install -y python"
  end

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "public_network", ip: "192.168.1.162"

    mysql.vm.provision  "shell",
      inline: "apt-get update && apt-get install -y python"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.160"

    ansible.vm.provision  "shell",
      inline: "cp /vagrant/.vagrant/machines/wordpress/virtualbox/private_key /home/vagrant/private_key_wordpress && \
              chmod 600 /home/vagrant/private_key_wordpress && \
              chown vagrant:vagrant /home/vagrant/private_key_wordpress"

    ansible.vm.provision  "shell",
      inline: "cp /vagrant/.vagrant/machines/mysql/virtualbox/private_key /home/vagrant/private_key_mysql && \
              chmod 600 /home/vagrant/private_key_mysql && \
              chown vagrant:vagrant /home/vagrant/private_key_mysql"

    ansible.vm.provision  "shell",
      inline: "cp /vagrant/hosts /home/vagrant && \
              chmod a-x /home/vagrant/hosts"

    ansible.vm.provision  "shell",
      inline: "cp /vagrant/provisioning.yml /home/vagrant"

    ansible.vm.provision  "shell",
      inline: "cp -r /vagrant/group_vars /home/vagrant"
    
    # ansible.vm.provision  "shell",
    #   inline: "cp -r /vagrant/templates /home/vagrant"
    
    ansible.vm.provision  "shell",
      inline: "cp -r /vagrant/roles /home/vagrant"

    ansible.vm.provision  "shell",
      inline: "apt-get update && \
              apt-get upgrade && \
              apt-get install -y software-properties-common && \
              add-apt-repository --yes --update ppa:ansible/ansible && \
              apt-get update
              apt install -y ansible"
  end
end
