---
- name: 'Add Repo php7.4'
  apt_repository:
    repo: 'ppa:ondrej/php'
  become: yes
- name: 'Update Repo'
  apt:
    update_cache: yes
  become: yes
- name: 'Install packages'
  apt: 
    name: [php7.4, apache2, libapache2-mod-php7.4, php7.4-gd, php-ssh2, php7.4-mcrypt, php7.4-mysql]
    state: latest
  become: yes
